### ISSUE TITLE
Mactex 2020

### ISSUE THREAD

**Issue by mattydee99** [autopkg/joshua-d-miller-recipes#83]
Is in an install loop. 
It looks like Munki checks for 4 receipts:
org.tug.mactex.ghostscript9.50
org.tug.mactex.ghostscript9.50libgs
org.tug.mactex.gui2020
org.tug.mactex.texlive2020
                   
I believe at least org.tug.mactex.ghostscript9.50libgs should be considered an optional receipt. Not all these components will be installed. Hence, Munki will attempt to reinstall Mactex on every run.

**Comment by joshua-d-miller** [comment]
Hello there!

I apologize for not getting this taken care of much sooner. I have gone ahead and updated the MacTeX recipe to create an installs array for one of the applications it installs which should mitigate the pkg receipt that does not install. In order to reflect this you will want to either remove your 2020 Version of MacTeX and add it again with AutoPKG or you can just create an installs array by using the following Command:

makepkginfo -f /Applications/TeX/LaTeXiT.app
